### ISSUE TITLE
Missing metadata fields in NBT presentation

### ISSUE THREAD

**Issue by EnnoMeijers** [CLARIAH/ineo-collaboration#1]
In the INEO presentation of the KB NBT dataset https://www.ineo.tools/resources/http_58__47__47_data.bibliotheken.nl_47_id_47_dataset_47_nbt a number of fields are missing such as description, publisher, date of issue

**Comment by menzowindhouwer** [comment]
description is now available on the dev server: https://ineo-git-development-eightmedia.vercel.app/resources/http_58__47__47_data.bibliotheken.nl_47_id_47_dataset_47_nbt :-) should hit the production server on monday

**Comment by EnnoMeijers** [comment]
Looks good now, closing this issue!
