### ISSUE TITLE
Combined English and Dutch text in one field 

### ISSUE THREAD

**Issue by EnnoMeijers** [CLARIAH/ineo-collaboration#2]
In the INEO presentation of dataset https://www.ineo.tools/resources/https_58__47__47_www.openarchieven.nl_47_id_47_foundlinkset-56abe4a6a2dc9e41a20485227bacbace the discription is a combination of the data in @nl and @en language fields.

**Comment by menzowindhouwer** [comment]
fixed in the dev version: https://ineo-git-development-eightmedia.vercel.app/resources/https_58__47__47_www.openarchieven.nl_47_id_47_foundlinkset-56abe4a6a2dc9e41a20485227bacbace :-) should hit production on monday

**Comment by EnnoMeijers** [comment]
Looks good now, closing this issue!
