### ISSUE TITLE
NDE datasets show DANS as resource host

### ISSUE THREAD

**Issue by EnnoMeijers** [CLARIAH/ineo-collaboration#3]
It looks like all the NDE-datasets show DANS as the resource host. This should be the publisher as stated in the NDE DCAT data. See for the datasets mentioned in issue #1 and #2 or https://ineo-git-development-eightmedia.vercel.app/resources/https_58__47__47_data.spinque.com_47_ld_47_data_47_netwerkoorlogsbronnen_47_beeldbank_zutphen_47_

**Comment by menzowindhouwer** [comment]
Sorry, that was a debug leak, i.e. this field was always filled by one single DANS record instead of the current record ... sorry, thanks for reporting! fixed locally, when the APIs work again the fix will hit the dev and prod servers ...

**Comment by EnnoMeijers** [comment]
Looks good now, closing this issue!
