### ISSUE TITLE
Unexpected "Page not found" error

### ISSUE THREAD

**Issue by EnnoMeijers** [CLARIAH/ineo-collaboration#4]
When searching for "linkset" the following dataset appears in the resultlist (as the forth result) but selecting the dataset results in the "Page not found" page.

Title: Linkset historische persoonsvermeldingen Rijksarchief België (Leu...
URL: https://www.ineo.tools/resources/https_58__47__47_www.openarchieven.nl_47_id_47_foundlinkset-f72a2d493b4ed480917599a1b9d66df9

**Comment by menzowindhouwer** [comment]
Werkt ondertussen ... tijdelijke glitch tijdens een update run?
